### ISSUE TITLE
syncedmem.hpp:39] Check failed: error == cudaSuccess (77 vs. 0)  an illegal memory access was encountered

### ISSUE THREAD

**Issue by nvnhann** [jasonppy/FaST-VGS-Family#1]
I exact features faster r-cnn flickr8k error: syncedmem.hpp:39] Check failed: error == cudaSuccess (77 vs. 0)  an illegal memory access was encountered

![image](https://user-images.githubusercontent.com/74455034/165105789-0e521aef-dedd-4482-813e-09455e0732a8.png)

config file:
![image](https://user-images.githubusercontent.com/74455034/165105931-8e7df52e-949e-4d85-b4d9-da9d082d696a.png)

can you help me fix error!

**Comment by jasonppy** [comment]
Hi,

Thanks for your interests. 

My feature extraction process follows closely [https://github.com/airsplay/lxmert#faster-r-cnn-feature-extraction](https://github.com/airsplay/lxmert#faster-r-cnn-feature-extraction), are you also following it and performing feature extraction in docker?

**Comment by nvnhann** [comment]
Hi,
I run it on google colab
Can you help me with these files?
I change
 SCALES: [250,]
 MAX_SIZE: 400
in
faster_rcnn_end2end_resnet.yml
but
not working ಥ‿ಥ !!

**Comment by jasonppy** [comment]
Sorry I could not provide help as I don't have any experience working google colab fast-rcnn feature extraction, I would recommend posting an issue under the whichever codebase you are using.

**Comment by nvnhann** [comment]
Thansk

Vào 4:26, Th 3, 26 thg 4, 2022 jasonppy ***@***.***> đã viết:
