### ISSUE TITLE
Exception has occurred: SystemExit 2 eroor

### ISSUE THREAD

**Issue by kilcimurat** [jasonppy/FaST-VGS-Family#2]
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Fast-VGS+ (debug)",
            "type": "python",
            "request": "launch",
            "program": "run_flickr8k.py",
            "console": "integratedTerminal",
            "justMyCode": true,
            "args": [
                "--data_root = ${/home/envisage/Desktop/Murat/FaST-VGS-Family-master/download_datasets/Datasets/flickr_audio}",
                "--raw_audio_base_path = ${/home/envisage/Desktop/Murat/FaST-VGS-Family-master/download_datasets/Datasets/flickr_audio/wavs}",
                "--fb_w2v2_weights_fn = ${/home/envisage/Desktop/Murat/audio_visual/FaST-VGS-Family-master}",
                "-exp_dir = ${/home/envisage/Desktop/Murat/FaST-VGS-Family-master/download_datasets/fast-vgs-flickr8k/fast-vgs-flickr8k}",
                "--num_workers = 4",
                "--batch_size = 96",
                "--val_batch_size = 100",
                "--val_cross_batch_size = 8000",
                "--n_epochs = 20",
                "--n_print_steps = 312",
                "--n_val_steps = 312",
                "--lr = 0.0001",
                "--warmup_fraction = 0.1",
                "--xtrm_layers = 2",
                "--trm_layers = 6",
                "--fine_matching_weight = 1.0",
                "--coarse_matching_weight = 0.1",
                "--coarse_to_fine_retrieve",
                "--feature_grad_mult = 0.",
                "--layer_use = 7"
            ]
        }
    ]
}

When we want to run the arguments in the script files from launch.json, we constantly get Exception has occurred: SystemExit 2 error. How can we debug using these arguments?

**Comment by jasonppy** [comment]
I'm not familiar with the platform are you using. For debugging purposes, could you try testing it in the interactive mode?

**Comment by kilcimurat** [comment]
Thank you for everything, I solved the this issue.
