### ISSUE TITLE
How to run the code

### ISSUE THREAD

**Issue by kilcimurat** [jasonppy/FaST-VGS-Family#3]
I am planning to use Fast VGS to extract features from a video using both audio and visual data. However, I am encountering various problems when trying to run the code to learn how to use the model. I am using Ubuntu 20.04 LTS and facing issues specifically with image feature extraction. I receive errors related to CUDA and the Ubuntu version when using the docker container 'airsplay/bottom-up-attention' provided for feature extraction. Additionally, I am experiencing problems with Fastercnn libraries while attempting to create a docker container myself. Can you assist me in running the code in an updated manner and guide me on how to effectively use the model?

**Comment by jasonppy** [comment]
as you are facing installation problems with the old faster-rcnn code, I would actually recommend you to try to use [VG-HuBERT](https://github.com/jasonppy/word-discovery) to extract features, it's a much simpler pipeline, it uses state-of-the-art self-supervised encoders (DINO and HuBERT), and the retrieval performance is almost as good as fast-vgs

**Comment by kilcimurat** [comment]
I will try this. thank you for your help
